### ISSUE TITLE
request: omit patch version in Cargo.toml

### ISSUE THREAD

**Issue by debris** [tailhook/abstract-ns#1]
I have a lib which uses `ns-dns-tokio`, `tokio-core` and `futures`. I'm unable to update `tokio` to latest version, cause `ns-dns-tokio` requires exact version - `0.1.0`.

```
cargo build -p p2p
Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `tokio-core` (required by `ns-dns-tokio`):
all possible versions conflict with previously selected versions of `tokio-core`
  version 0.1.1 in use by tokio-core v0.1.1
  possible versions to select: 0.1.0
```

Can you omit patch version in `Cargo.toml` files? Use `0.1` instead of `0.1.0`

**Comment by tailhook** [comment]
This is a known thing. Just run `cargo update` to fix this issue.

**Comment by debris** [comment]
I did, output remains the same

**Comment by tailhook** [comment]
Is there a repo somewhere so I can try?

Here is how versions work: If you specify "0.1.2" it means any "0.1" starting from "0.1.2". And "0.1" means exactly the same as "0.1.0"

Basically, this kind of conflicts is a bug/feature in cargo. It's probably just too cautious. In older versions of cargo I've usually removed `Cargo.lock` and let cargo rebuild it to fix this kind of conflicts. But  nowadays `cargo update` is usually sufficient.

**Comment by debris** [comment]
> Is there a repo somewhere so I can try?

No, but I will prepare a way to reproduce it and I will report it upstream.

> Basically, this kind of conflicts is a bug/feature in cargo. It's probably just too cautious. In older versions of cargo I've usually removed Cargo.lock

It worked. I used to do the same, but recently it was not needed. Thanks!
