### ISSUE TITLE
crates.io / git version mismatch for ns-dns-tokio

### ISSUE THREAD

**Issue by TimNN** [tailhook/abstract-ns#4]
The currently published version of `ns-dns-tokio` on crates.io is `0.3`, however https://github.com/tailhook/abstract-ns/blob/master/ns-dns-tokio/Cargo.toml has a version of `0.2`, which seems kinda inconsistent (and makes things annoying when using a git url and a `version` field in the dependency specification).

**Comment by tailhook** [comment]
Yes, it's super-strange, I'll recheck that on my other laptop tomorrow and publish a new version.

**Comment by tailhook** [comment]
Fixed. Thank you for report!
