### ISSUE TITLE
Reconsider Port Handling (or rather: mention them in the documentation)

### ISSUE THREAD

**Issue by TimNN** [tailhook/abstract-ns#5]
I was recently *very* surprised to receive the following error message from this crate: `error: name "foo.example.com" is invalid: SRV records are not supported, please specify default port`: Nowhere in the crate documentation (at least not where I could find it) was a `default port` mentioned, and it came as a huge surprise that this crate would even concern itself with the concept of ports.

(My primary entrypoint was the `ns-dns-tokio` crate. While writing this issue I actually read the readme of `abstract-ns` and just came to the conclusion that the purpose of this crate is simply not what I wanted it to be (simple DNS resolution)).

Well anyway I propose that either of the following is done:

* Improve the documentation with regard to port handling
* Modify the crate to work with plain ip addresses although that probably goes contrary to the purpose of this crate

**Comment by tailhook** [comment]
Finally, I've decided to split it into [four traits](https://github.com/tailhook/abstract-ns/blob/23603f8ab563cd518045255f51f9328dbd242786/src/lib.rs#L7-L19) to make it more clear. Please, take a look into current master.
