### ISSUE TITLE
please publish ns-dns-tokio updates to crates.io

### ISSUE THREAD

**Issue by olix0r** [tailhook/abstract-ns#9]
Hello,

It seems that the latest release of ns-dns-tokio published to crates.io is [0.4.0](https://crates.io/crates/ns-dns-tokio). When you have a moment, can you please publish 0.4.2?

Thank you!

**Comment by tailhook** [comment]
The version of `ns-dns-tokio` doesn't have to match the version of `abstract-ns`. We have `abstract-ns` of 0.4.2, but `ns-dns-tokio` did non change since 0.4.0. So it's up to date on crates.io.

Is there any scenario with these libraries that doesn't work for you?

**Comment by olix0r** [comment]
Ah, my apologies. I must have gotten into an odd cargo state and couldn't get the abstract-ns update to compile initially.  Thanks for clarifying.
